### ISSUE TITLE
special treatment for resigned delegates

### ISSUE THREAD

**Issue by qsvtr** [unik-name/unikname-network-delegates-website#47]
it would be interesting to have a treatment for the delegates who are resigned

what would be the most suitable option?
 - not to display them 
- display them with an explicit banner

**Comment by dlecan** [comment]
Removing them?

We can also add the link at the bottom to the full list of delegates: https://explorer.unikname.network/delegates/

**Comment by qsvtr** [comment]
yep i think it's the better option
good idea for the link

**Comment by Nigui** [comment]
This link may be better because it has a tab to list resigned delegates https://explorer.unikname.network/delegate-status
